apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_DATABASE
          value: qlbandoannhanh
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user-password
        ports:
        - containerPort: 3306
        resources:
          requests:
            memory: "512Mi"  # Reduced memory request
            cpu: "500m"      # Reduced CPU request
          limits:
            memory: "1Gi"    # Reduced memory limit
            cpu: "1"         # Reduced CPU limit
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: mysql-config
          mountPath: /etc/mysql/conf.d
        startupProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 30  # Allow up to 5 minutes for startup
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 120  # Increased delay
          periodSeconds: 10
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 120  # Increased delay
          periodSeconds: 10
          failureThreshold: 5
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-initdb
        configMap:
          name: mysql-init
      - name: mysql-config
        configMap:
          name: mysql-config
