apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    # Tối ưu hóa InnoDB để khởi động nhanh hơn
    innodb_buffer_pool_size=512M
    innodb_log_file_size=128M
    innodb_doublewrite=0  # Tắt doublewrite buffer (chỉ dùng trong môi trường phát triển)
    [client]
    # default-character-set=utf8mb4
    [mysql]
    # default-character-set=utf8mb4
