apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
data:
  apache.conf: |
    <Directory /var/www/html>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
