apiVersion: v1
kind: ConfigMap
metadata:
  name: php-code-content
data:
  "config.php": |
    <?php
    $mysqli = new mysqli("mysql-service", "app_user", "app_password", "doannhanh_db");
    if ($mysqli->connect_error) {
        die("Connection failed: " . $mysqli->connect_error);
    }
    ?>
  "navtop.php": |
    <?php
    echo "<div class='nav-top'>Navigation Top</div>";
    ?>
  "navmenu.php": |
    <?php
    echo "<div class='nav-menu'>Navigation Menu</div>";
    ?>
  "main.php": |
    <?php
    echo "<div class='main-content'>Main Content</div>";
    ?>
  "footer.php": |
    <?php
    echo "<div class='footer'>Footer</div>";
    ?> 