apiVersion: batch/v1
kind: Job
metadata:
  name: copy-php-code
spec:
  template:
    spec:
      containers:
      - name: copy-files
        image: busybox:1.35
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Starting copy process...";
          mkdir -p /target;
          echo "Copying from /source to /target";
          cp -r /source/* /target/;
          echo "Setting permissions...";
          chown -R 33:33 /target;
          chmod -R 755 /target;
          echo "Verifying contents...";
          ls -la /target;
          echo "Copy process completed.";
        volumeMounts:
        - name: source
          mountPath: /source
        - name: target
          mountPath: /target
      volumes:
      - name: source
        configMap:
          name: php-code
      - name: target
        persistentVolumeClaim:
          claimName: php-pvc
      restartPolicy: Never