apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: php:8.0-apache
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: php-code-volume
          mountPath: /var/www/html
        command: ["/bin/sh", "-c"]
        args:
        - |
          apt-get update &&           apt-get install -y libpq-dev &&           docker-php-ext-install pdo pdo_mysql &&           cp /var/www/html/index.php /var/www/html/index.php.bak 2>/dev/null || true &&           cp /code-config/index.php /var/www/html/ &&           chmod 644 /var/www/html/index.php &&           apache2-foreground
      volumes:
      - name: php-code-volume
        configMap:
          name: php-code
