apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    SET NAMES utf8mb4;
    SET CHARACTER SET utf8mb4;
    SET character_set_connection=utf8mb4;
    SET character_set_database=utf8mb4;
    SET character_set_results=utf8mb4;
    SET character_set_server=utf8mb4;
    SET collation_connection=utf8mb4_unicode_ci;
    SET collation_database=utf8mb4_unicode_ci;
    SET collation_server=utf8mb4_unicode_ci;
    
    CREATE DATABASE IF NOT EXISTS qlbandoannhanh CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    USE qlbandoannhanh;
    
    -- Tạo user và cấp quyền
    CREATE USER IF NOT EXISTS 'app_user'@'%' IDENTIFIED BY 'dXNlcnBhc3M';
    GRANT ALL PRIVILEGES ON qlbandoannhanh.* TO 'app_user'@'%';
    FLUSH PRIVILEGES;
    
    -- Tạo bảng users
    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(50) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL,
        email VARCHAR(100) NOT NULL UNIQUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    
    -- Tạo bảng restaurants
    CREATE TABLE IF NOT EXISTS restaurants (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        address TEXT NOT NULL,
        phone VARCHAR(20),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    
    -- Tạo bảng orders
    CREATE TABLE IF NOT EXISTS orders (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        restaurant_id INT NOT NULL,
        total_amount DECIMAL(10,2) NOT NULL,
        status VARCHAR(20) DEFAULT 'pending',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (user_id) REFERENCES users(id),
        FOREIGN KEY (restaurant_id) REFERENCES restaurants(id)
    ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; 