apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    innodb_buffer_pool_size=512M
    innodb_log_file_size=128M
    innodb_doublewrite=0
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    [client]
    [mysql]
