apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: php-app-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: php-app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mysql
  endpoints:
  - port: mysql
    interval: 15s 