apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-code-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/php-code
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-code-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 