apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/thinboonny/doannhanh/phpCode
  persistentVolumeReclaimPolicy: Retain