apiVersion: v1
kind: ServiceAccount
metadata:
  name: php-app-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: php-app-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: php-app-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: php-app-sa
  namespace: default
roleRef:
  kind: Role
  name: php-app-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: mysql-sa
  namespace: default
roleRef:
  kind: Role
  name: mysql-role
  apiGroup: rbac.authorization.k8s.io 