apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: cm9vdHBhc3M=        # echo -n "rootpass" | base64
  user-password: dXNlcnBhc3M=        # echo -n "userpass" | base64
  database: cWxiYW5kb2Fubmhhbmg=    # echo -n "qlbandoannhanh" | base64
  username: YXBwX3VzZXI=             # echo -n "app_user" | base64