apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: default
  annotations:
    kubernetes.io/service-account.name: mysql-sa
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: $(echo -n "your-secure-password" | base64)
  MYSQL_DATABASE: $(echo -n "your-database" | base64)
  MYSQL_USER: $(echo -n "your-user" | base64)
  MYSQL_PASSWORD: $(echo -n "your-password" | base64)
---
apiVersion: v1
kind: Secret
metadata:
  name: php-app-secrets
  namespace: default
  annotations:
    kubernetes.io/service-account.name: php-app-sa
type: Opaque
data:
  DB_HOST: $(echo -n "mysql-service" | base64)
  DB_NAME: $(echo -n "your-database" | base64)
  DB_USER: $(echo -n "your-user" | base64)
  DB_PASSWORD: $(echo -n "your-password" | base64)
  APP_KEY: $(echo -n "your-app-key" | base64)
---
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
  namespace: default
type: Opaque
data:
  JWT_SECRET: $(echo -n "your-jwt-secret" | base64)
  API_KEY: $(echo -n "your-api-key" | base64) 