version: '3.8'

services:
  # Dịch vụ PHP và Apache
  php-app:
    build:
      context: ../  # Trỏ đến thư mục gốc
      dockerfile: docker/Dockerfile
    container_name: php_app
    ports:
      - "8080:80"  # Ánh xạ cổng 8080 của máy host vào cổng 80 của container
    volumes:
      - ../phpCode:/var/www/html
      - ../phpCode/admin:/var/www/html/admin
      - ./docker/apache:/etc/apache2/sites-available
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    depends_on:
      - mysql_db  # Đơn giản hóa phần depends_on
    networks:
      - app_network
    restart: always  # Tự động khởi động lại nếu có lỗi
  
  # Dịch vụ MySQL
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: qlbandoannhanh
      MYSQL_USER: app_user
      MYSQL_PASSWORD: userpass
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"  # Ánh xạ cổng MySQL
    volumes:
      - mysql_data:/var/lib/mysql  # Lưu trữ dữ liệu MySQL
      - ../phpCode/database:/docker-entrypoint-initdb.d  # Script khởi tạo database
    networks:
      - app_network
    restart: always  # Tự động khởi động lại nếu có lỗi

# Định nghĩa volumes
volumes:
  mysql_data:  # Volume lưu trữ dữ liệu MySQL

# Định nghĩa networks
networks:
  app_network:
    driver: bridge  # Sử dụng bridge network để kết nối các container