version: "3.8"

services:
  # FRONTEND - Người dùng
  php-app:
    build:
      context: .               # Dockerfile nằm cùng cấp
      dockerfile: Dockerfile
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./phpCode:/var/www/html
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    command: >
      sh -c "chown -R www-data:www-data /var/www/html && apache2-foreground"
    depends_on:
      - mysql-service
    networks:
      - app_network
    restart: always

  # ADMIN - Quản trị
  php-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_admin
    ports:
      - "8081:80"
    volumes:
      - ./phpCode/admin:/var/www/html
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    command: >
      sh -c "chown -R www-data:www-data /var/www/html && apache2-foreground"
    depends_on:
      - mysql-service
    networks:
      - app_network
    restart: always

  # Dịch vụ MySQL
  mysql-service:
    image: mysql:8.0
    container_name: mysql-service
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: qlbandoannhanh
      MYSQL_USER: app_user
      MYSQL_PASSWORD: userpass
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./phpCode/database:/docker-entrypoint-initdb.d
    networks:
      - app_network
    restart: always

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
