apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=
  MYSQL_DATABASE: cWxiYW5kb2Fubmhhbmg=
  MYSQL_USER: YXBwX3VzZXI=
  MYSQL_PASSWORD: dXNlcnBhc3M=
---
apiVersion: v1
kind: Secret
metadata:
  name: php-app-secrets
  namespace: default
type: Opaque
data:
  DB_HOST: bXlzcWwtc2VydmljZQ==
  DB_NAME: cWxiYW5kb2Fubmhhbmg=
  DB_USER: YXBwX3VzZXI=
  DB_PASSWORD: dXNlcnBhc3M=
  APP_KEY: YXBwa2V5
---
apiVersion: v1
kind: Secret
metadata:
  name: php-admin-secrets
  namespace: default
type: Opaque
data:
  DB_HOST: bXlzcWwtc2VydmljZQ==
  DB_NAME: cWxiYW5kb2Fubmhhbmg=
  DB_USER: YXBwX3VzZXI=
  DB_PASSWORD: dXNlcnBhc3M=
  APP_KEY: YWRtaW5fYXBwa2V5
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-secrets
  namespace: default
type: Opaque
data:
  CF_TUNNEL_CREDENTIALS: eyJBY2NvdW50VGFnIjoieW91ci1hY2NvdW50LXRhZyIsIlR1bm5lbFNlY3JldCI6InlvdXItdHVubmVsLXNlY3JldCIsIlR1bm5lbElEIjoiMTIzNC01Njc4LTkwMTIifQ==
