name: CI/CD Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, curl, mysql, pdo, pdo_mysql
    
    - name: Install dependencies
      run: |
        composer install --no-interaction --prefer-dist
    
    - name: Run PHPUnit tests
      run: |
        vendor/bin/phpunit
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and test Docker image
      run: |
        docker build -t buithienboo/qlbandoannhanh-php-app:test .
        docker run --rm buithienboo/qlbandoannhanh-php-app:test php vendor/bin/phpunit
        
    - name: Run security scan
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy image buithienboo/qlbandoannhanh-php-app:test
        
    - name: Run kube-bench
      run: |
        docker run --rm -v `pwd`:/host aquasec/kube-bench:latest install
        ./kube-bench
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker images
      run: |
        docker build -t buithienboo/qlbandoannhanh-php-app:latest .
        docker build -t buithienboo/auth-service:latest ./auth-service
        docker push buithienboo/qlbandoannhanh-php-app:latest
        docker push buithienboo/auth-service:latest
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
        
    - name: Verify deployment
      run: |
        kubectl rollout status deployment/php-app
        kubectl rollout status deployment/auth-service
        kubectl get pods
        
    - name: Run post-deployment tests
      run: |
        # Wait for services to be ready
        sleep 30
        # Test PHP application
        curl -s http://localhost:8080/health
        # Test Auth service
        curl -s http://localhost:8081/health
        
  monitor:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        
    - name: Check application health
      run: |
        kubectl port-forward svc/php-app 8080:80 &
        sleep 5
        curl -s http://localhost:8080/health | grep "ok"
        
    - name: Check metrics
      run: |
        kubectl port-forward svc/prometheus-server 9090:9090 &
        sleep 5
        curl -s http://localhost:9090/metrics | grep "php_"
        
    - name: Check logs
      run: |
        kubectl logs -l app=php-app --tail=100
        kubectl logs -l app=auth-service --tail=100
        
    - name: Check resources
      run: |
        kubectl top pods
        kubectl top nodes 